axis_linear:
  x: 1
  y: 0
scale_linear:
  x: -0.5
  y: -0.5
scale_linear_turbo:
  x: -1.4
  y: -1.4
axis_angular:
  yaw: 2
scale_angular:
  yaw: -0.7
scale_angular_turbo:
  yaw: -2.0
enable_button: 4
enable_turbo_button: 5
